Ds4 58 send start command to assembly station
SDU-F23/SDU-F23-Semester-Project pull request #22
Opened 2023-04-19 13:34 UTC by Siole

Merges DS52 into DS58 due to troubles with too many similarities

2023-04-19 13:44 UTC, 3FCO requested changes

2023-04-19 13:44 UTC, 3FCO commented on backend/Assembly/src/main/java/dk/sdu/controllab/assembly/service/AssemblyServiceImpl.java
> +    private static GetStatusResponse latestStatus;
This shouldn't be static

2023-04-19 13:44 UTC, 3FCO commented on backend/Assembly/src/main/java/dk/sdu/controllab/assembly/service/AssemblyServiceImpl.java
> +    private String[] message = {""};
Java doesn't compile with these ``@Resources`` and therefore doesn't run
```suggestion
    private IMqttClient client;
    @Value("false")
    private boolean isHealthy;
    private GetStatusResponse latestStatus;
    private String[] message = {""};
```

2023-04-19 13:59 UTC, Siole commented on backend/Assembly/src/main/java/dk/sdu/controllab/assembly/service/AssemblyServiceImpl.java
> +    private static GetStatusResponse latestStatus;
Agreed - thought I'd already fixed that - well it's fixed now :-)

2023-04-20 11:29 UTC, 3FCO approved these changes
Godt arbejde! 🫡

2023-04-20 11:39 UTC, merged