Feature/ds4-42 Setup foundation for recipes
SDU-F23/SDU-F23-Semester-Project pull request #4
Opened 2023-04-04 19:24 UTC by MagnusHJensen

2023-04-05 10:34 UTC, Siole commented on backend/application/pom.xml
modules uses Pascal in the class diagram

2023-04-05 10:44 UTC, Siole commented on backend/commonrecipe/pom.xml
> +        <plugins>
Is the plugin needed? Asking coz I'm not sure

2023-04-05 10:44 UTC, Siole commented on backend/commonrecipe/src/main/java/dk/sdu/controllab/commonrecipe/CreateRecipeRequest.java
> +public record CreateRecipeRequest(List<UUID> inputIds, UUID outputId) {
Doesn't match the class diagram

2023-04-05 10:44 UTC, Siole commented on backend/pom.xml
> +        <module>commonrecipe</module>
Pascal

2023-04-05 10:44 UTC, Siole commented on backend/recipe/pom.xml
> +    <build>
Plugin needed?

2023-04-05 10:44 UTC, Siole commented on backend/commonrecipe/src/main/java/dk/sdu/controllab/commonrecipe/UpdateRecipeRequest.java
> +public record UpdateRecipeRequest(List<UUID> inputIds, UUID outputId) {
Doesn't match class diagram

2023-04-13 12:28 UTC, Siole requested changes
Tag stilling til record.

2023-04-13 12:28 UTC, Siole commented on backend/CommonRecipe/src/main/java/dk/sdu/controllab/commonrecipe/CreateRecipeRequest.java
> +public record CreateRecipeRequest(List<UUID> inputItemIds, UUID outputItemId) {
Hvorfor er det her en record og ikke en @getter?

2023-04-13 12:28 UTC, Siole commented on backend/CommonRecipe/src/main/java/dk/sdu/controllab/commonrecipe/UpdateRecipeRequest.java
> +public record UpdateRecipeRequest(List<UUID> inputItemIds, UUID outputItemId) {
no Spring annotation?

2023-04-14 14:08 UTC, MagnusHJensen commented on backend/CommonRecipe/src/main/java/dk/sdu/controllab/commonrecipe/UpdateRecipeRequest.java
> +public record UpdateRecipeRequest(List<UUID> inputItemIds, UUID outputItemId) {
Nope, det her er bare en POJO (Plain Old Java Object) klasse.

2023-04-15 08:12 UTC, Siole approved these changes

2023-04-18 11:22 UTC, merged